import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js tutorial",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
     
     <body className={`${inter.className} bg-white`}>
          <Navbar />
          <main className="px-8 py-20 max-w-6xl mx-auto">
            <Provider>
            {children}
              </Provider>
              </main>
        </body>
    </html>
  );
}
